// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxYfD_kHJnpGQxcwL2CbU-TpuZXKFX0Lc',
    appId: '1:828975209032:web:8277188ca20233eb46567d',
    messagingSenderId: '828975209032',
    projectId: 'signup-52627',
    authDomain: 'signup-52627.firebaseapp.com',
    storageBucket: 'signup-52627.appspot.com',
    measurementId: 'G-QKZZL2HKF6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZ_KTTwtBbuk9-cZEMFkSsW436EXyxg20',
    appId: '1:828975209032:android:6a2690d9922e105846567d',
    messagingSenderId: '828975209032',
    projectId: 'signup-52627',
    storageBucket: 'signup-52627.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUfkYDV5BFTJjj9dv4osD4UlC4G75k6OM',
    appId: '1:828975209032:ios:8f9321e24eeb073046567d',
    messagingSenderId: '828975209032',
    projectId: 'signup-52627',
    storageBucket: 'signup-52627.appspot.com',
    iosBundleId: 'com.example.signup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUfkYDV5BFTJjj9dv4osD4UlC4G75k6OM',
    appId: '1:828975209032:ios:8063e4600f440c1446567d',
    messagingSenderId: '828975209032',
    projectId: 'signup-52627',
    storageBucket: 'signup-52627.appspot.com',
    iosBundleId: 'com.example.signup.RunnerTests',
  );
}
